### PR TITLE
Updated worm DE tutorial to use new API

### PR DESCRIPTION
**Pull request by Munfred**
Hello, I finished updating the worm DE tutorial to use new API. I also added an example of using `scvi.data.poisson_gene_selection` to select genes.

I'm not 100% sure if my descriptions of `raw_mean` and `raw_normalized_mean` (copied below) are correct. In the docstring of `model.differential_expression` description of the returned object it only says "Returns: Differential expression DataFrame." It would be good if you could update the docstring to include a description of what each column in the returned DataFrame is.

Thanks! 

--- 
### Print the differential expression results
- `bayes_factor`: The bayes factor for cell type 1 having a higher expression than cell type 2
- `proba_m`**`i`**: p-value for cell type **i** having higher expression than the other
- `raw_mean`**`i`**: the average number of UMI counts sampled cell type **i** during the DE. Because scvi is a generative model, it is generating new cells and counting how many times each gene is sampled to compute the DE.
- `raw_normalized_mean`**`i`**: the average UMI counts sampled cell type **i** weighted by the number of draws made.

- `non_zeros_proportion`**`i`**: proportion of non-zero expression in cell type **i**
- `norm_mean`**`i`**: average UMI counts in cell type **i** normalized by cell size
- `scale`**`i`**: average scVI inferred gene expression scale in cell type **i**. This is the same value that can be obtained using `model.get_normalized_expression()` using `library_size=1`, equivalent to the "expression frequency" of the gene: what fraction of the UMIs sampled from that cell would belong to that gene.

### CODE REVIEW

**Comment by adamgayoso** [comment]
I will review this soon. Thanks for contributing!

**Comment by adamgayoso** [comment]
I can't review this notebook as is I think because it was directly imported from Colab. Could you download locally and open and save with your local jupyter? Also it would be helpful if you overwrite the notebook of yours in the `contributed` directory.

**Comment by adamgayoso** [comment]
### Print the differential expression results
- `bayes_factor`: The bayes factor for cell type 1 having a higher expression than cell type 2
- `proba_m`**`i`**: p-value for cell type **i** having higher expression than the other
- `raw_mean`**`i`**: the average UMI counts for gene in group **i**
- `raw_normalized_mean`**`i`**: the average library-size normalized expression for gene in group **i**

- `non_zeros_proportion`**`i`**: proportion of non-zero expression in cell type **i**
- `scale`**`i`**: average scVI inferred gene expression scale in cell type **i**. This is the same value that can be obtained using `model.get_normalized_expression()` using `library_size=1`, equivalent to the "expression frequency" of the gene: what fraction of the UMIs sampled from that cell would belong to that gene. 

Where do you see `norm_mean`?

**Comment by Munfred** [comment]
Ah sorry the `norm_mean` is old, I missed removing it. My doubts are about what `raw_mean` and `raw_normalized_mean` are.

I'm gonna submit a new PR with the notebook overwrite

**Comment by adamgayoso** [comment]
Sorry I had put the definition in the post above

`raw_mean` is just the average UMI count for all the cells in that group.

`raw_normalized_mean` is the average library size normalized expression for that group (divide by library size, multiply by 10,000).

**Pull request closed without merging**
